### ISSUE TITLE
Latest patch update still shows conflicts

### ISSUE THREAD

**Issue by eldiener** [mikael-s-persson/templight#13]
The latest updated patch still shows conflicts wit the latest clang.

**Comment by wmamrak** [comment]
It is ok here.

**Comment by eldiener** [comment]
I was wrong and it is OK also. Applying the path using TortoiseSVN on Windows gave some "rejected hunks" messages which made me think that the patch had failed. But it actually succeeded and the rejected "hunks" were just:

--- include/clang/FrontendTool/Utils.h	(revision 236501)
+++ include/clang/FrontendTool/Utils.h	(working copy)

--- include/clang/Sema/Sema.h	(revision 236501)
+++ include/clang/Sema/Sema.h	(working copy)

and

--- lib/Parse/ParseAST.cpp	(revision 236501)
+++ lib/Parse/ParseAST.cpp	(working copy)

I do not know why these were "rejected hunks" but looking at the files patched the patch succeeded.

**Comment by mikael-s-persson** [comment]
The revisions on LLVM and Clang are very fast paced, which means that even when the templight patch to clang is only 1 day old, its revision number is already many many revisions behind the trunk of llvm/clang. Usually, the patch will apply correctly despite that revision number mismatch, as long as svn can figure it out. From time to time, the changes accumulated over time make it impossible for svn to apply the patch on its own, just like what you reported earlier in issue #12, which just means that I had to resolve the conflict manually and generate a new patch.

The point is, it's possible that your SVN application (TortoiseSVN) is reporting those revision number mismatches as errors, even when the patch was applied successfully. This is just something you have to live with.
