### ISSUE TITLE
cl::StringSaver has changed to latest revisions

### ISSUE THREAD

**Issue by apmanol** [mikael-s-persson/templight#18]
Currently in the head of 	http://llvm.org/git/clang.git i.e 979403f for my case the cl::StringSaver has been replaced with llvm::StringSaver utility. So the code doesn't compile, with errors in 
templight_driver.cpp

**Comment by mikael-s-persson** [comment]
Thanks for pointing this out. I've been very busy lately and I couldn't get to fixing this for some time, because they (clang devs) have made significant changes to their frontend / driver code which required me to make significant changes too, to match theirs, as best as possible.
