### ISSUE TITLE
Patch outdated

### ISSUE THREAD

**Issue by schulmar** [mikael-s-persson/templight#19]
I tried to build with revision 242644 and get the following errors:
```
llvm/tools/clang/lib/Sema/SemaType.cpp: In function »bool handleObjCOwnershipTypeAttr({anonymous}::TypeProcessingState&, clang::AttributeList&, clang::QualType&)«:
llvm/tools/clang/lib/Sema/SemaType.cpp:5148:5: Error: expected »}« before »else«
     else if (Def && TemplateInstCallbacksChain) {
```
Patch already produced some warnings but no error.
Upon inspection I discovered, that there is an already existing else branch at this location and the patch added another one.

**Comment by mikael-s-persson** [comment]
Thanks. The patch and the driver code was very outdated. I fixed it. It should work now.
