### ISSUE TITLE
Templight fails with -gsplit-dwarf

### ISSUE THREAD

**Issue by cout** [mikael-s-persson/templight#24]
pbrannan@telx-sb-dev2:~/tmp $ cat test.cpp
template<typename T> class Foo { };
pbrannan@telx-sb-dev2:~/tmp $ ~/svn/llvm/build/Release+Asserts/bin/templight++ -Xtemplight -profiler test.cpp -gsplit-dwarf 2>&1 | head -20
templight: error: unknown argument: '--extract-dwo'
/tmp/test-fa7506.o:1:1: error: expected identifier or '('
<U+007F>ELF<U+0002><U+0001><U+0001>
^
/tmp/test-fa7506.o:1:8: warning: null character ignored
<U+007F>ELF<U+0002><U+0001><U+0001>
                                   ^
/tmp/test-fa7506.o:1:9: warning: null character ignored
<U+007F>ELF<U+0002><U+0001><U+0001><U+0000>
                                           ^
/tmp/test-fa7506.o:1:10: warning: null character ignored
<U+007F>ELF<U+0002><U+0001><U+0001><U+0000><U+0000>
                                                   ^
/tmp/test-fa7506.o:1:11: warning: null character ignored
<U+007F>ELF<U+0002><U+0001><U+0001><U+0000><U+0000><U+0000>
                                                           ^
/tmp/test-fa7506.o:1:12: warning: null character ignored
<U+007F>ELF<U+0002><U+0001><U+0001><U+0000><U+0000><U+0000><U+0000>
                                                                   ^
/tmp/test-fa7506.o:1:13: warning: null character ignored

**Comment by r0mai** [comment]
It seems to work for me. What clang version did you try to apply the patch to? The current version of the patch was made against r242645. Maybe it didn't apply correctly to your version.

Also, reordering the arguments might help (putting -gsplit-dwarf in front for example).

The error you are getting is not templight related I think. Even though it says `templight: error:` clang just uses the drivers name as the prefix in that line. Maybe you could try the same with clang++ instead of templight++, to see if it works with plain clang.

**Comment by cout** [comment]
I applied latest templight (0426a4) to r250921.  Patch applied cleanly.

I also tried a slightly older templight (fe14ed) against clang 3.7.0 and got the same error.

Reordering arguments makes no difference.  I have tried various combinations:
    templight++ -gsplit-dwarf -Xtemplight -profiler test.cpp
    templight++ -Xtemplight -profiler -gsplit-dwarf test.cpp
    templight++ -Xtemplight -profiler test.cpp -gsplit-dwarf
    templight++ test.cpp -gsplit-dwarf -Xtemplight -profiler
    templight++ -gsplit-dwarf test.cpp -Xtemplight -profiler

Running without -Xtemplight also produces an error:
    templight++ -gsplit-dwarf test.cpp

Running with patched clang++ instead of templight++ does not produce any error output:
    clang++ -gsplit-dwarf test.cpp

I'm not sure what's going on here.  The compiler should be running:
    /usr/bin/objcopy --extract-dwo /tmp/test-XXXXXX.o test.dwo
    /usr/bin/objcopy --strip-two /tmp/test-XXXXXX.o

Output from clang++ and templight++ using -v (this is the 3.7 build I mentioned above):

pbrannan@telx-sb-dev2:~/tmp $ clang++-3.7 -v -gsplit-dwarf test.cpp            
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/pbrannan/opt/clang-3.7.0/bin/clang-3.7" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name test.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -v -dwarf-column-info -g -backend-option -split-dwarf=Enable -resource-dir /home/pbrannan/opt/clang-3.7.0/bin/../lib/clang/3.7.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward -internal-isystem /usr/local/include -internal-isystem /home/pbrannan/opt/clang-3.7.0/bin/../lib/clang/3.7.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/pbrannan/tmp -ferror-limit 19 -fmessage-length 168 -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/test-1ca454.o -x c++ test.cpp -split-dwarf-file test.dwo
clang -cc1 version 3.7.0 based upon LLVM 3.7.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward
 /usr/local/include
 /home/pbrannan/opt/clang-3.7.0/bin/../lib/clang/3.7.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
 "/usr/bin/objcopy" --extract-dwo /tmp/test-1ca454.o test.dwo
 "/usr/bin/objcopy" --strip-dwo /tmp/test-1ca454.o
 "/usr/bin/ld" -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.8/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. -L/home/pbrannan/opt/clang-3.7.0/bin/../lib -L/lib -L/usr/lib /tmp/test-1ca454.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/4.8/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o

pbrannan@telx-sb-dev2:~/tmp $ templight++-3.7 -v -gsplit-dwarf test.cpp 2>&1 | head -50
clang version 3.7.0 (tags/RELEASE_370/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
clang -cc1 version 3.7.0 based upon LLVM 3.7.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8
 /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward
 /usr/local/include
 /home/pbrannan/opt/clang-3.7.0/bin/../lib/clang/3.7.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
templight-3.7: error: unknown argument: '--extract-dwo'

**Comment by mikael-s-persson** [comment]
It is highly unlikely that there is any meaningful interaction between the templight-specific code (in semantic analysis) and the code that relates to this option (on code generation). This issue seems to be a problem with clang, not with templight.
