### ISSUE TITLE
update for the latest svn trunk of llvm/clang

### ISSUE THREAD

**Issue by tahsinH** [mikael-s-persson/templight#38]
The llvm/clang code has moved along and I am not able to build templight with the latest version 

llvm/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp:219:68: error: no viable conversion from 'clang::Sema::ActiveTemplateInstantiation' to
      'const clang::ActiveTemplateInstantiation'
      SemaRef.TemplateInstCallbacksChain->atTemplateBegin(SemaRef, Inst);
1.  As a sidenote, couple of suggestions, instead of saying use the latest svn revision for clang/llvm. May be a specific version should be specified. That way, while the maintainers work on updating the underlying code , other people can go ahead and build it. 
2. I also like the metashell approach and provide a way to just get a binary version. 
   Or, there was a talk about providing a docker version. For people who want to just demo the use case , it would be an easier starting point. 

By the way, thanks to the maintainers. I did not get a chance to use it fully, but used the metashell online version and saw llvm conference video. Really a superb tool for template programmers.

**Comment by dvzubarev** [comment]
For anyone who wants to build templight at the present moment.
You need to use 0738fa15ef7e24c5864c95e02d53c6f2e98f160b version of templight and 289544 revision of llvm/clang.

**Comment by bluehood** [comment]
thank you. this should definitely be specified in the readme though

**Comment by elelel** [comment]
I think README instructions should not refer to "latest trunk version" but rather specify (probably latest) compatible revision pairs for LLVM/CLANG and templight. There's little hope that latest trunk stays compatible with the diffs for a long time.

**Comment by ofloveandhate** [comment]
firmly agree with @elelel .  readme leaves me wanting for specific version information so that the patch can apply cleanly.  as of today, using revision 301787 of clang and 301782 of llvm, the patching step did not complete correctly.

**Comment by renemilk** [comment]
I would really like to check out the current state of templight, but I'm also stopped by having the right combination of revisions.

**Comment by Szelethus** [comment]
Good news, the templight patch was merged a couple weeks ago, and the README now reflects this as well.

**Comment by bluehood** [comment]
Hi, afaict the README still suggests to build templight against the "latest" clang.
This is bound to break at some point in the future, isn't it?

**Comment by Szelethus** [comment]
That's a fair point. We've just added 2 new branches for LLVM/Clang version 5.0 and 6.0, those are very unlikely to ever break.

**Comment by asomerville-latai** [comment]
@mikael-s-persson  I think this one can be closed as fixed

**Comment by mikael-s-persson** [comment]
@asomerville-latai Thanks for pointing it out. Yeah, I think this is fixed, at least, I got everything to work again not too long ago, so it should be working until further notice.
