### ISSUE TITLE
It is unclear which clang release this should be built with

### ISSUE THREAD

**Issue by armanschwarz** [mikael-s-persson/templight#6]
This is probably mostly a matter of documentation, but I followed the instructions in the Readme and pulled clang 3.5 release source from the repo.

During the Patch step I got several warnings, like:

Skipped missing target: 'include/clang/Sema/ActiveTemplateInst.h'
Skipped missing target: 'include/clang/Sema/TemplateInstObserver.h'
Skipped missing target: 'lib/Sema/ActiveTemplateInst.cpp'

And finally:

Summary of conflicts:
  Text conflicts: 6
  Skipped paths: 3

When I attempted to build I got the following error:

/home/user/llvm-templight-v2/tools/clang/include/clang/Driver/Options.td:187:1: error: def 'templight' already defined
def templight : Flag<["-"], "templight">, Group<f_Group>, Flags<[CC1Option]>,
^

Would you be able to add some comments to the documentation which outline which revision of clang this patch was tested with?

**Comment by cout** [comment]
I have also run into this; the documentation says to use "latest svn trunk", but occasionally templight development is a little bit behind clang development and things don't compile cleanly.  Including the exact svn revision in the templight commit messages would help alleviate this issue.

For clang releases, the following SHAs apply cleanly:

3.6.2 - f4b0b7
3.7.0 - fe14ed

**Comment by r0mai** [comment]
There is an open patch for clang, to merge this upstream. That merge will solve this problem once and for all. If you want to follow: http://reviews.llvm.org/D5767

Also, there is actually a PR, which updates the patch for a more recent clang (and a couple of new features): #25. You might be able to use the patch in that PR, if the current one doesn't apply cleanly.

**Comment by mikael-s-persson** [comment]
The patch is generated from SVN, and therefore, the revision number is always stated for every file that it modifies. The current patch is for revision 251760.
