### ISSUE TITLE
How to build this tool?

### ISSUE THREAD

**Issue by Warchant** [mikael-s-persson/templight#60]
I follow an instruction in README on master and end up with 

```
tools/clang/tools/templight/TemplightDebugger.h:13:45: fatal error: clang/Sema/TemplateInstCallback.h: No such file or directory

tools/clang/tools/templight/TemplightTracer.h:13:45: fatal error: clang/Sema/TemplateInstCallback.h: No such file or directory

tools/clang/tools/templight/TemplightTracer.h:13:45: fatal error: clang/Sema/TemplateInstCallback.h: No such file or directory

tools/clang/tools/templight/templight_driver.cpp:383:87: error: ‘CreateFrontendAction’ was not declared in this scope
   std::unique_ptr<TemplightAction> Act(new TemplightAction(CreateFrontendAction(*Clang)));
```

independently of llvm/clang version (I tried latest, release_40, release_50, release_60).

Can somebody point me to a specific commit version of templight and llvm/clang revisions which can be built?

**Comment by Szelethus** [comment]
I had no issue building with these versions:
LLVM git: 930bcc9bdfb9542a292c3de874d7e6ba1464cfe0
LLVM svn: https://llvm.org/svn/llvm-project/llvm/trunk@325569
clang git: 6eb4766e65557933c30152738c47e6ff34a1d216
clang svn: https://llvm.org/svn/llvm-project/cfe/trunk@325571

Will look into this issue.

**Comment by Szelethus** [comment]
Did you try building with those versions? Any success?

**Comment by Warchant** [comment]
It worked. 
Templight git commit: 1478d7a1a60174819ede4c9aba92d171674cb9ab
LLVM git: 930bcc9bdfb9542a292c3de874d7e6ba1464cfe0
clang git: 6eb4766e65557933c30152738c47e6ff34a1d216
