### ISSUE TITLE
can't compile templight with latest clang version

### ISSUE THREAD

**Issue by gergol** [mikael-s-persson/templight#63]
I followed the instructions on compiling templight, but the compilation fails when compiling the `templight_driver.cpp` with the following output: 

`[2204/2480] Building CXX object tools/clang/tools/templight/CMakeFiles/templight.dir/templight_driver.cpp.o
FAILED: tools/clang/tools/templight/CMakeFiles/templight.dir/templight_driver.cpp.o
/usr/bin/c++   -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/tools/templight -I/mnt/d/windows/wsl_data/llvm6/llvm/tools/clang/tools/templight -I/mnt/d/windows/wsl_data/llvm6/llvm/tools/clang/include -Itools/clang/include -Iinclude -I/mnt/d/windows/wsl_data/llvm6/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG    -fno-exceptions -fno-rtti -MMD -MT tools/clang/tools/templight/CMakeFiles/templight.dir/templight_driver.cpp.o -MF tools/clang/tools/templight/CMakeFiles/templight.dir/templight_driver.cpp.o.d -o tools/clang/tools/templight/CMakeFiles/templight.dir/templight_driver.cpp.o -c /mnt/d/windows/wsl_data/llvm6/llvm/tools/clang/tools/templight/templight_driver.cpp
/mnt/d/windows/wsl_data/llvm6/llvm/tools/clang/tools/templight/templight_driver.cpp: In function ‘int main(int, const char**)’:
/mnt/d/windows/wsl_data/llvm6/llvm/tools/clang/tools/templight/templight_driver.cpp:489:24: error: ‘GetArgumentVector’ is not a member of ‘llvm::sys::Process’
   std::error_code EC = llvm::sys::Process::GetArgumentVector(
                        ^
[2207/2480] Building CXX object tools/clang/tools/templight/CMakeFiles/templight.dir/TemplightDebugger.cpp.o
ninja: build stopped: subcommand failed.`

My System is Ubuntu 16.04 on Windows via WSL. 

I think I've already spotted the cause: They removed the `llvm::sys::Process::GetArgumentVector` just a few hours ago :-( . See: https://reviews.llvm.org/D45641 

I guess it shouldn't be too difficult to fixi it for somone familiar who is (unlike me) familiar with the clang source code.

**Comment by ricejasonf** [comment]
They annotated the revisions that they had it working with in a recent PR.
https://github.com/mikael-s-persson/templight/pull/62

**Comment by gergol** [comment]
Thanks Jason, that helped.
