### ISSUE TITLE
Fail to compile with latest llvm git repo

### ISSUE THREAD

**Issue by prudhomm** [mikael-s-persson/templight#81]
following compilation instruction does not work.

`llvm/tools/clang/tools` is not seen by the cmake process

Adding a CMakeLists.txt with add_clang_subdirectory in llvm/tools/clang does something but `add_clang_subdirectory` is unknown

**Comment by prudhomm** [comment]
I managed to do it.
actually the documentation should state `llvm/clang/tools` rather than `llvm/tools/clang/tools`

**Comment by lauzi** [comment]
But I don't `llvm/clang` folder in the llvm-project repo?
